#!/bin/sh
# https://superuser.com/a/337640/39302
case "$1" in
    *.awk|*.js|*.coffee|*.css|*.php|*.pl|*.sh|\
    *.inc|*.xml|*.diff|*.patch|*.py|*.rb|*.sql|\
    *.haml)
        pygmentize -f 256 "$1";;
    .bashrc|.bash_aliases|.bash_environment)
        pygmentize -f 256 -l sh "$1"
        ;;
    *)
        grep "#\!/bin/bash" "$1" > /dev/null
        if [ "$?" -eq "0" ]; then
            pygmentize -f 256 -l sh "$1"
        else
            exit 1
        fi
esac

exit 0

