#!/usr/bin/env bash
set -euo pipefail

ROOT="${ROOT:-$HOME/dotfiles}"
WITH_NVIDIA=0

. /etc/os-release

if [ "${1:-}" = "--nvidia" ]; then
  WITH_NVIDIA=1
fi

ensure_repo_bootstrap_tools() {
  sudo apt-get update
  sudo apt-get install -y ca-certificates curl gnupg
}

add_hyprland_ppa() {
  # Ubuntu 24.04 LTS and 25.10 both rely on the cppiber Hyprland PPA for the
  # current Hyprland stack this dotfiles repo expects.
  if [ "${VERSION_ID:-}" = "25.10" ]; then
    ensure_repo_bootstrap_tools
    sudo install -d -m 0755 /etc/apt/keyrings
    curl -fsSL 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xFDBAAA1CF0CCF48E' \
      | gpg --dearmor \
      | sudo tee /etc/apt/keyrings/cppiber-hyprland.gpg >/dev/null
    cat <<EOF | sudo tee /etc/apt/sources.list.d/cppiber-hyprland.sources >/dev/null
Types: deb
URIs: https://ppa.launchpadcontent.net/cppiber/hyprland/ubuntu
Suites: questing
Components: main
Signed-By: /etc/apt/keyrings/cppiber-hyprland.gpg
EOF
  elif [ "${VERSION_ID:-}" = "24.04" ]; then
    sudo add-apt-repository -y universe || true
    sudo add-apt-repository -y ppa:cppiber/hyprland || true
  fi
}

if [ "${VERSION_ID:-}" = "24.04" ] || [ "${VERSION_ID:-}" = "25.10" ]; then
  add_hyprland_ppa
fi

sudo apt update

package_available() {
  [ "$(apt-cache policy "$1" 2>/dev/null | awk '/Candidate:/{print $2; exit}')" != "(none)" ]
}

pick_first_available() {
  for pkg in "$@"; do
    if package_available "$pkg"; then
      echo "$pkg"
      return 0
    fi
  done
  return 1
}

BASE_PACKAGES=(
  blueman
  cliphist
  curl
  dtrx
  fonts-font-awesome
  fonts-jetbrains-mono
  fonts-noto-color-emoji
  fonts-symbola
  fzf
  git
  grim
  hypridle
  hyprland
  hyprlock
  hyprpicker
  hyprsunset
  jq
  kitty
  network-manager-gnome
  nm-tray
  nwg-displays
  nwg-look
  pavucontrol
  playerctl
  qt5ct
  qt6ct
  slurp
  sway-notification-center
  thunar
  waybar
  wl-clipboard
  wlogout
  xdg-desktop-portal-hyprland
  yad
  zsh
  zsh-syntax-highlighting
)

OPTIONAL_APT_PACKAGES=(
  fastfetch
  starship
  swappy
)

INSTALL_PACKAGES=("${BASE_PACKAGES[@]}")
for pkg in "${OPTIONAL_APT_PACKAGES[@]}"; do
  if package_available "$pkg"; then
    INSTALL_PACKAGES+=("$pkg")
  else
    printf 'Skipping unavailable APT package: %s\n' "$pkg"
  fi
done

for pkg in hyprland-qt-support0 "$(pick_first_available hyprland-qtutils hyprland-guiutils || true)"; do
  if [ -n "${pkg:-}" ] && package_available "$pkg"; then
    INSTALL_PACKAGES+=("$pkg")
  elif [ -n "${pkg:-}" ]; then
    printf 'Skipping unavailable APT package: %s\n' "$pkg"
  fi
done

sudo apt install -y "${INSTALL_PACKAGES[@]}"

"$ROOT/setup/install-rofi-wayland.sh"
"$ROOT/setup/install-ags-v1.sh"
"$ROOT/setup/install-nerd-fonts.sh"
"$ROOT/setup/configure-google-chrome-wayland.sh"
"$ROOT/setup/install-wallust.sh"
"$ROOT/setup/install-satty.sh"
"$ROOT/setup/install-yazi.sh"

if ! command -v fastfetch >/dev/null 2>&1; then
  "$ROOT/setup/install-fastfetch.sh"
fi

if ! command -v swappy >/dev/null 2>&1; then
  "$ROOT/setup/install-swappy.sh"
fi

if [ "$WITH_NVIDIA" = "1" ]; then
  sudo ubuntu-drivers install
  cat > "$ROOT/config/hypr/gpu-nvidia.conf" <<'EOF'
# Nvidia overrides generated by setup/ubuntu.sh --nvidia
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
env = GBM_BACKEND,nvidia-drm
EOF
fi
